name: py3
channels:
  - conda-forge
  - nest
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - aiohappyeyeballs=2.4.4
  - aiohttp=3.11.10
  - aiosignal=1.2.0
  - alabaster=0.7.16
  - aom=3.9.1
  - applaunchservices=0.3.0
  - appnope=0.1.4
  - arrow=1.3.0
  - astroid=3.2.4
  - asttokens=3.0.0
  - asyncssh=2.17.0
  - atomicwrites=1.4.0
  - attrs=24.2.0
  - autopep8=2.0.4
  - babel=2.11.0
  - beautifulsoup4=4.12.3
  - binaryornot=0.4.4
  - black=24.8.0
  - blas=1.0
  - bleach=6.2.0
  - bottleneck=1.4.2
  - brian2=2.7.1
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2026.1.4
  - cached-property=1.5.2
  - cairo=1.16.0
  - cairocffi=1.7.1
  - cairosvg=2.8.2
  - cctools_osx-64=986
  - certifi=2026.1.4
  - cffi=1.17.1
  - chardet=4.0.0
  - charset-normalizer=3.3.2
  - clang=17.0.6
  - clang-17=17.0.6
  - clang_impl_osx-64=17.0.6
  - clang_osx-64=17.0.6
  - clangxx=17.0.6
  - clangxx_impl_osx-64=17.0.6
  - clangxx_osx-64=17.0.6
  - click=8.1.7
  - cloudpickle=3.0.0
  - cmake=3.26.4
  - comm=0.2.2
  - compiler-rt=17.0.6
  - compiler-rt_osx-64=17.0.6
  - contourpy=1.3.1
  - cookiecutter=2.6.0
  - cryptography=43.0.3
  - cssselect2=0.8.0
  - cycler=0.11.0
  - cyrus-sasl=2.1.28
  - cython=3.0.11
  - dav1d=1.2.1
  - debugpy=1.6.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - deprecated=1.2.13
  - diff-match-patch=20200713
  - dill=0.3.8
  - docstring-to-markdown=0.11
  - docutils=0.18.1
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - expat=2.6.3
  - ffmpeg=7.0.1
  - flake8=7.1.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.51.0
  - freetype=2.12.1
  - fribidi=1.0.10
  - frozenlist=1.5.0
  - gdk-pixbuf=2.42.10
  - gettext=0.25.1
  - gettext-tools=0.25.1
  - giflib=5.2.2
  - glib=2.78.4
  - glib-tools=2.78.4
  - gmp=6.3.0
  - gnutls=3.7.9
  - graphite2=1.3.14
  - gsl=2.7.1
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - h5py=3.13.0
  - harfbuzz=10.2.0
  - hdf5=1.14.3
  - icu=73.1
  - idna=3.7
  - imageio=2.33.1
  - imagesize=1.4.1
  - importlib-metadata=8.5.0
  - inflection=0.5.1
  - intervaltree=3.1.0
  - ipykernel=6.29.5
  - ipython=8.30.0
  - ipywidgets=8.1.8
  - isort=5.13.2
  - jaraco.classes=3.2.1
  - jedi=0.19.2
  - jellyfish=1.0.1
  - jinja2=3.1.4
  - joblib=1.4.2
  - jpeg=9e
  - jsonschema=4.23.0
  - jsonschema-specifications=2023.7.1
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - jupyterlab_pygments=0.2.2
  - jupyterlab_widgets=3.0.16
  - kaleido-core=0.2.1
  - keyring=24.3.1
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lame=3.100
  - lcms2=2.12
  - ld64_osx-64=711
  - leptonica=1.82.0
  - lerc=3.0
  - libabseil=20240116.2
  - libaec=1.1.3
  - libarchive=3.6.2
  - libasprintf=0.25.1
  - libasprintf-devel=0.25.1
  - libass=0.17.1
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libclang=14.0.6
  - libclang-cpp17=17.0.6
  - libclang13=14.0.6
  - libcurl=8.11.1
  - libcxx=19.1.5
  - libcxx-devel=17.0.6
  - libdeflate=1.17
  - libedit=3.1.20230828
  - libev=4.33
  - libexpat=2.6.3
  - libffi=3.4.4
  - libgettextpo=0.25.1
  - libgettextpo-devel=0.25.1
  - libgfortran=5.0.0
  - libgfortran5=13.2.0
  - libglib=2.78.4
  - libhwloc=2.12.1
  - libiconv=1.18
  - libidn2=2.3.8
  - libintl=0.25.1
  - libintl-devel=0.25.1
  - liblapack=3.9.0
  - libllvm14=14.0.6
  - libllvm17=17.0.6
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libnghttp2=1.57.0
  - libogg=1.3.5
  - libopenblas=0.3.21
  - libopenvino=2024.1.0
  - libopenvino-auto-batch-plugin=2024.1.0
  - libopenvino-auto-plugin=2024.1.0
  - libopenvino-hetero-plugin=2024.1.0
  - libopenvino-intel-cpu-plugin=2024.1.0
  - libopenvino-ir-frontend=2024.1.0
  - libopenvino-onnx-frontend=2024.1.0
  - libopenvino-paddle-frontend=2024.1.0
  - libopenvino-pytorch-frontend=2024.1.0
  - libopenvino-tensorflow-frontend=2024.1.0
  - libopenvino-tensorflow-lite-frontend=2024.1.0
  - libopus=1.3.1
  - libpng=1.6.39
  - libpq=17.2
  - libprotobuf=4.25.3
  - librsvg=2.56.3
  - libsodium=1.0.18
  - libspatialindex=1.9.3
  - libsqlite=3.46.0
  - libssh2=1.11.1
  - libtasn1=4.20.0
  - libtheora=1.1.1
  - libtiff=4.5.1
  - libtool=2.4.7
  - libunistring=0.9.10
  - libuv=1.48.0
  - libvorbis=1.3.7
  - libvpx=1.14.1
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxml2=2.13.8
  - libxslt=1.1.43
  - libzlib=1.2.13
  - llvm-openmp=20.1.1
  - llvm-tools=17.0.6
  - lxml=5.2.2
  - lz4-c=1.9.4
  - lzo=2.10
  - macosx_deployment_target_osx-64=10.13
  - markdown-it-py=2.2.0
  - markupsafe=2.1.3
  - mathjax=2.7.7
  - matplotlib=3.9.2
  - matplotlib-base=3.9.2
  - matplotlib-inline=0.1.7
  - mccabe=0.7.0
  - mdurl=0.1.0
  - mistune=2.0.4
  - more-itertools=10.3.0
  - mpi=1.0
  - mpmath=1.3.0
  - multidict=6.1.0
  - mypy_extensions=1.0.0
  - mysql=8.4.0
  - nbclient=0.8.0
  - nbconvert=7.16.4
  - nbformat=5.10.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - nest-simulator=3.7
  - nettle=3.9.1
  - numexpr=2.10.1
  - numpy=1.26.4
  - numpy-base=1.26.4
  - numpydoc=1.7.0
  - openh264=2.4.1
  - openjpeg=2.5.2
  - openldap=2.6.4
  - openmpi=4.1.6
  - openssl=3.6.0
  - p11-kit=0.24.1
  - packaging=24.2
  - pandas=2.2.3
  - pandocfilters=1.5.0
  - pango=1.50.14
  - parso=0.8.4
  - pathspec=0.10.3
  - patsy=1.0.1
  - pcre2=10.42
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.0.0
  - pip=24.2
  - pixman=0.40.0
  - platformdirs=4.3.6
  - plotly=5.24.1
  - pluggy=1.5.0
  - ply=3.11
  - prompt-toolkit=3.0.48
  - propcache=0.2.0
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pugixml=1.14
  - pure_eval=0.2.3
  - pycodestyle=2.12.1
  - pycparser=2.21
  - pydocstyle=6.3.0
  - pyflakes=3.2.0
  - pygithub=2.4.0
  - pygments=2.18.0
  - pyjwt=2.9.0
  - pylint=3.2.7
  - pylint-venv=3.0.3
  - pyls-spyder=0.4.0
  - pynacl=1.5.0
  - pyobjc-core=10.1
  - pyobjc-framework-cocoa=10.1
  - pyobjc-framework-coreservices=10.1
  - pyobjc-framework-fsevents=10.1
  - pyparsing=3.2.0
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - pyqtwebengine=5.15.10
  - pysocks=1.7.1
  - python=3.12.2
  - python-dateutil=2.9.0.post0
  - python-fastjsonschema=2.20.0
  - python-kaleido=0.2.1
  - python-lsp-black=2.0.0
  - python-lsp-jsonrpc=1.1.2
  - python-lsp-server=1.12.0
  - python-slugify=5.0.2
  - python-tzdata=2023.3
  - python.app=3
  - python_abi=3.12
  - pytoolconfig=1.2.6
  - pytz=2024.1
  - pyuca=1.2
  - pyyaml=6.0.2
  - pyzmq=25.1.2
  - qdarkstyle=3.2.3
  - qstylizer=0.2.2
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtawesome=1.3.1
  - qtconsole=5.6.0
  - qtpy=2.4.1
  - readline=8.2
  - referencing=0.30.2
  - requests=2.32.3
  - rhash=1.4.3
  - rich=13.9.4
  - rope=1.12.0
  - rpds-py=0.10.6
  - rtree=1.0.1
  - scikit-learn=1.5.1
  - scipy=1.14.1
  - seaborn=0.13.2
  - setuptools=72.1.0
  - sigtool=0.1.3
  - sip=6.7.12
  - six=1.17.0
  - snappy=1.2.2
  - snowballstemmer=2.2.0
  - sortedcontainers=2.4.0
  - soupsieve=2.5
  - sphinx=7.3.7
  - sphinxcontrib-applehelp=1.0.2
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=2.0.0
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml=1.1.10
  - spyder=6.0.1
  - spyder-kernels=3.0.0
  - sqlite=3.45.3
  - stack_data=0.6.3
  - statsmodels=0.14.4
  - superqt=0.6.7
  - svgutils=0.3.4
  - svt-av1=2.1.0
  - sympy=1.13.2
  - tabulate=0.9.0
  - tapi=1100.0.11
  - tbb=2022.3.0
  - tenacity=9.0.0
  - tesseract=5.2.0
  - text-unidecode=1.3
  - textdistance=4.6.3
  - threadpoolctl=3.5.0
  - three-merge=0.1.1
  - time=1.8
  - tinycss2=1.2.1
  - tk=8.6.14
  - tomli=2.0.1
  - tomlkit=0.13.2
  - tornado=6.4.2
  - traitlets=5.14.3
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2024b
  - ujson=5.10.0
  - unicodedata2=15.1.0
  - unidecode=1.3.8
  - urllib3=2.2.3
  - watchdog=4.0.1
  - wcwidth=0.2.13
  - webencodings=0.5.1
  - whatthepatch=1.0.2
  - wheel=0.44.0
  - widgetsnbextension=4.0.15
  - wrapt=1.14.1
  - wurlitzer=3.0.2
  - x264=1!164.3095
  - x265=3.5
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - yaml=0.2.5
  - yapf=0.40.2
  - yarl=1.18.0
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - absl-py==2.3.0
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==21.2.0
      - arviz==0.21.0
      - cachetools==6.1.0
      - cons==0.4.6
      - etuples==0.3.9
      - filelock==3.18.0
      - find-libpython==0.4.0
      - fsspec==2025.5.1
      - grpcio==1.73.0
      - h5netcdf==1.6.1
      - ipython-genutils==0.2.0
      - logical-unification==0.4.6
      - markdown==3.8.2
      - minikanren==1.0.4
      - multipledispatch==1.0.0
      - networkx==3.5
      - neuron==8.2.6
      - nflows==0.14
      - notebook==6.4.12
      - opt-einsum==3.4.0
      - prometheus-client==0.22.1
      - protobuf==6.31.1
      - pyknos==0.16.0
      - pymc==5.23.0
      - pyro-api==0.1.2
      - pyro-ppl==1.9.1
      - pytensor==2.31.3
      - sbi==0.24.0
      - send2trash==1.8.3
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - terminado==0.18.1
      - toolz==1.0.0
      - torch==2.2.2
      - tqdm==4.67.1
      - werkzeug==3.1.3
      - xarray==2025.6.1
      - xarray-einstats==0.9.1
      - zuko==1.4.1
prefix: /opt/anaconda3/envs/py3
